// doc: https://firebase.google.com/docs/auth/admin/errors?hl=es-419
export const FIREBASE_ERRORS: Record<string, string> = {
   'auth/account-exists-with-different-credential': 'Account already exists with a different credential.',
   'auth/email-already-in-use': 'The email address is already in use.',
   'auth/invalid-email': 'The email address is invalid.',
   'auth/missing-email': 'The email address is missing.',
   'auth/wrong-password': 'The password is incorrect.',
   'auth/user-not-found': 'The user is not found.',
   'auth/weak-password': 'The password is too weak.',
   'auth/invalid-credential': 'The credential is invalid.',
   'auth/internal-error': 'An internal error has occurred.',
   'auth/unauthorized-error': 'You are not authorized to perform this action.',
   'auth/too-many-requests': 'There are too many requests. Please try again later.',
   'auth/operation-not-allowed': 'This operation is not allowed.',
   'auth/user-disabled': 'The user is disabled.',
   'auth/user-token-expired': 'The user token has expired.',
   'auth/invalid-user-token': 'The user token is invalid.',
   'auth/recaptcha-verification-failed': 'The reCAPTCHA verification failed.',
   'auth/phone-number-already-exists': 'The phone number already exists.',
   'auth/invalid-phone-number': 'The phone number is invalid.',
   'auth/missing-phone-number': 'The phone number is missing.',
   'auth/code-verification-failed': 'The code verification failed.',
   'auth/credential-too-young': 'The credential is too young.',
   'auth/account-deleted': 'The account has been deleted.',
   'auth/timeout': 'The request timed out.',
   'auth/captcha-check-failed': 'The reCAPTCHA check failed.',
   'auth/invalid-oauth-provider': 'The OAuth provider is invalid.',
   'auth/oauth-issuer-error': 'An error occurred with the OAuth issuer.',
   'auth/oauth-access-token-expired': 'The OAuth access token has expired.',
   'auth/oauth-invalid-credential': 'The OAuth credential is invalid.',
   'auth/oauth-unauthorized-client-error': 'The OAuth client is unauthorized.',
   'auth/sign-in-failed': 'The sign-in failed.',
   'auth/provider-already-linked': 'The provider is already linked to an account.',
   'auth/no-provider-found': 'No provider was found for the given request.',
   'auth/email-verification-failed': 'The email verification failed.',
   'auth/email-link-expired': 'The email link has expired.',
   'auth/phone-number-verification-failed': 'The phone number verification failed.',
   'auth/firebase-server-error': 'A Firebase server error has occurred.',
   'auth/app-not-authorized': 'The app is not authorized to perform this action.',
   'auth/invalid-custom-token': 'The custom token is invalid.',
   'auth/custom-token-expired': 'The custom token has expired.',
   'auth/credenital-mismatch': 'The credential mismatch.',
   'auth/missing-android-pkg-name': 'The Android package name is missing.',
   'auth/invalid-android-pkg-name': 'The Android package name is invalid.',
   'auth/missing-ios-bundle-id': 'The iOS bundle ID is missing.',
   'auth/invalid-ios-bundle-id': 'The iOS bundle ID is invalid.',
   'auth/unauthorized-domain': 'The domain is unauthorized.',
   'auth/invalid-domain': 'The domain is invalid.',
   'auth/token-claims-error': 'There was an error with the token claims.',
   'auth/admin-error': 'An error occurred while performing an admin action.',
   'auth/token-expired': 'The token has expired.',
   'auth/account-change-requires-reauthentication': 'Account change requires reauthentication.',
   'auth/session-expired': 'The session has expired.',
   'auth/user-mismatch': 'The user mismatch.',
   'auth/quota-exceeded': 'The quota has been exceeded.',
   'auth/missing-uid': 'The UID is missing.',
   'auth/can-not-delete-user': 'The user cannot be deleted.'
};
